version: '3'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy-net
    restart: unless-stopped

  influx:
    image: influxdb:latest
    networks:
      - influx-net
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    networks:
      - reverse-proxy-net
      - mosquitto-net
      - influx-net
    volumes:
      - ./node-red-data:/data
    labels:
      - "traefik.http.routers.nodered.rule=PathPrefix(`/node-red`)"
      - "traefik.docker.network=pi-server_reverse-proxy-net"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      - "GF_SECURITY_COOKIE_SECURE=false"
      - "GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/"
    networks:
      - reverse-proxy-net
      - influx-net
    labels:
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
      - "traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana"
      - "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
      - "traefik.docker.network=pi-server_reverse-proxy-net"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    restart: unless-stopped
    networks:
      - mosquitto-net

networks:
  reverse-proxy-net:
  mosquitto-net:
  influx-net:
