version: '3'

services:
  # Internal sensor
  ds18b20-28-051760c72dff:
    image: ds18b20-mqtt:latest
    command: 28-051760c72dff serverpi.lan
    restart: unless-stopped

  # External sensor
  ds18b20-28-051760c6b1ff:
    image: ds18b20-mqtt:latest
    command: 28-051760c6b1ff serverpi.lan
    restart: unless-stopped

  rtl_433:
    image: rtl_433:latest
    command: -d 0 -M newmodel -F mqtt://serverpi.lan,devices=rtl_433/devices[/type][/model][/subtype][/channel][/id]
    privileged: true
    restart: unless-stopped
