version: '3'

services:
  reverse-proxy:
    image: traefik:2.0.4
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - ./volumes/reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy-net
    restart: unless-stopped

  influx:
    image: influxdb:1.7.8-alpine
    networks:
      - influx-net
    restart: unless-stopped

  node-red:
    image: nodered/node-red:1.0.2-12-minimal
    networks:
      - reverse-proxy-net
      - mosquitto-net
      - influx-net
    volumes:
      - ./volumes/node-red-data:/data
    labels:
      - "traefik.http.routers.nodered.rule=PathPrefix(`/node-red`)"
      - "traefik.docker.network=serverpi_reverse-proxy-net"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:6.3.6
    environment:
      - "GF_SECURITY_COOKIE_SECURE=false"
      - "GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/"
    networks:
      - reverse-proxy-net
      - influx-net
    labels:
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
      - "traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana"
      - "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
      - "traefik.docker.network=serverpi_reverse-proxy-net"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:1.6.7
    ports:
      - "1883:1883"
    restart: unless-stopped
    networks:
      - mosquitto-net

networks:
  reverse-proxy-net:
  mosquitto-net:
  influx-net:
